export type ModelType = "frontier" | "open-source";
export type Modality = "text" | "image" | "video" | "audio" | "code";

export interface AIModel {
  id: string;
  name: string;
  provider: string;
  providerColor: string;
  type: ModelType;
  releaseDate: string;      // ISO "YYYY-MM-DD"
  family: string;           // Model family/generation, e.g. "Claude 4.6", "GPT-5.4"
  variantLabel?: string;    // Short display label for column view, e.g. "Opus", "Pro"
  // Benchmarks — null = not publicly disclosed
  mmlu?: number;            // 0-100, general knowledge
  gpqa?: number;            // 0-100, PhD-level science reasoning
  sweBench?: number;        // 0-100, software engineering tasks
  // Cost — 0 for self-hosted open-source
  costInput: number;        // $/1M tokens
  costOutput: number;       // $/1M tokens
  speedTPS?: number;        // approx tokens/sec
  contextK: number;         // context window in K tokens
  modalities: Modality[];
  tags: string[];
  notes?: string;
}

// ── Provider colours ────────────────────────────────────────────────────────
const C = {
  anthropic:  "#f59e0b",
  openai:     "#10b981",
  google:     "#4285f4",
  meta:       "#a855f7",
  xai:        "#ef4444",
  deepseek:   "#60a5fa",
  alibaba:    "#06b6d4",
  mistral:    "#f97316",
  nvidia:     "#76b900",
  aws:        "#ff9900",
  microsoft:  "#0078d4",
} as const;

export const AI_MODELS: AIModel[] = [

  // ── Anthropic ──────────────────────────────────────────────────────────────
  {
    id: "claude-opus-46",
    name: "Claude Opus 4.6",
    provider: "Anthropic",
    providerColor: C.anthropic,
    type: "frontier",
    releaseDate: "2026-02-05",
    family: "Claude 4.6",
    variantLabel: "Opus",
    gpqa: 91.3,
    sweBench: 80.8,
    contextK: 1000,
    costInput: 5,
    costOutput: 25,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Reasoning", "Agent-Ready"],
    notes: "Leads Chatbot Arena coding Elo (1561); Agent Teams support; 1M context at standard pricing",
  },
  {
    id: "claude-sonnet-46",
    name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    providerColor: C.anthropic,
    type: "frontier",
    releaseDate: "2026-02-17",
    family: "Claude 4.6",
    variantLabel: "Sonnet",
    sweBench: 79.6,
    contextK: 1000,
    costInput: 3,
    costOutput: 15,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Best for Coding", "Agent-Ready"],
    notes: "Improved computer use and instruction following; 1M context at standard pricing",
  },
  {
    id: "claude-37-sonnet",
    name: "Claude 3.7 Sonnet",
    provider: "Anthropic",
    providerColor: C.anthropic,
    type: "frontier",
    releaseDate: "2025-02-24",
    family: "Claude 3.7",
    variantLabel: "Sonnet",
    gpqa: 84.8,
    sweBench: 70.3,
    contextK: 200,
    costInput: 3,
    costOutput: 15,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Extended Thinking", "Best for Coding"],
    notes: "Extended thinking mode for complex reasoning chains",
  },
  {
    id: "claude-35-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    providerColor: C.anthropic,
    type: "frontier",
    releaseDate: "2024-10-22",
    family: "Claude 3.5",
    variantLabel: "Sonnet",
    mmlu: 88.7,
    gpqa: 65.0,
    sweBench: 49.0,
    contextK: 200,
    costInput: 3,
    costOutput: 15,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Best for Coding"],
    notes: "Set new SWE-Bench record on release; strong instruction following and tool use",
  },
  {
    id: "claude-35-haiku",
    name: "Claude 3.5 Haiku",
    provider: "Anthropic",
    providerColor: C.anthropic,
    type: "frontier",
    releaseDate: "2024-11-05",
    family: "Claude 3.5",
    variantLabel: "Haiku",
    contextK: 200,
    costInput: 0.80,
    costOutput: 4.00,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Fastest", "Cheapest"],
    notes: "Fastest Claude 3.5; ideal for high-throughput tasks",
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus",
    provider: "Anthropic",
    providerColor: C.anthropic,
    type: "frontier",
    releaseDate: "2024-03-04",
    family: "Claude 3",
    variantLabel: "Opus",
    mmlu: 86.8,
    gpqa: 50.4,
    contextK: 200,
    costInput: 15,
    costOutput: 75,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Reasoning"],
    notes: "Flagship Claude 3; best at nuanced analysis and complex instructions",
  },
  {
    id: "claude-3-haiku",
    name: "Claude 3 Haiku",
    provider: "Anthropic",
    providerColor: C.anthropic,
    type: "frontier",
    releaseDate: "2024-03-07",
    family: "Claude 3",
    variantLabel: "Haiku",
    mmlu: 75.2,
    contextK: 200,
    costInput: 0.25,
    costOutput: 1.25,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Fastest", "Cheapest"],
    notes: "Fastest, most compact Claude 3 model",
  },

  // ── OpenAI ─────────────────────────────────────────────────────────────────
  {
    id: "gpt-54-pro",
    name: "GPT-5.4 Pro",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2026-03-05",
    family: "GPT-5.4",
    variantLabel: "Pro",
    mmlu: 88.5,
    gpqa: 92.0,
    sweBench: 80,
    contextK: 1000,
    costInput: 30,
    costOutput: 180,
    modalities: ["text", "image", "audio", "code"],
    tags: ["Frontier", "Multimodal", "Reasoning"],
    notes: "Top-tier GPT-5.4; OSWorld computer use 75% — above human expert baseline",
  },
  {
    id: "gpt-54",
    name: "GPT-5.4",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2026-03-05",
    family: "GPT-5.4",
    variantLabel: "Standard",
    mmlu: 88.5,
    gpqa: 92.0,
    sweBench: 80,
    contextK: 1000,
    costInput: 2.5,
    costOutput: 15,
    modalities: ["text", "image", "audio", "code"],
    tags: ["Frontier", "Multimodal", "Agent-Ready"],
    notes: "33% fewer factual errors vs GPT-5.2; Tool Search architecture; computer use",
  },
  {
    id: "gpt-54-mini",
    name: "GPT-5.4 Mini",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2026-03-17",
    family: "GPT-5.4",
    variantLabel: "Mini",
    contextK: 400,
    costInput: 0.75,
    costOutput: 4.50,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Efficient", "Cheapest"],
    notes: "Mid-tier GPT-5.4; strong price-to-performance ratio",
  },
  {
    id: "gpt-54-nano",
    name: "GPT-5.4 Nano",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2026-03-17",
    family: "GPT-5.4",
    variantLabel: "Nano",
    contextK: 400,
    costInput: 0.20,
    costOutput: 1.25,
    modalities: ["text", "code"],
    tags: ["Frontier", "Cheapest", "Fastest"],
    notes: "Ultra-cheap for high-volume, latency-sensitive tasks",
  },
  {
    id: "gpt-53-codex",
    name: "GPT-5.3 Codex",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2026-02-24",
    family: "GPT-5.3",
    variantLabel: "Codex",
    contextK: 200,
    costInput: 2.0,
    costOutput: 10,
    modalities: ["text", "code"],
    tags: ["Frontier", "Best for Coding", "Agent-Ready"],
    notes: "Agentic coding specialist; multi-file refactors in a single response",
  },
  {
    id: "o3",
    name: "o3",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2025-04-16",
    family: "o3",
    variantLabel: "o3",
    gpqa: 87.7,
    sweBench: 69.1,
    contextK: 128,
    costInput: 10,
    costOutput: 40,
    modalities: ["text", "code"],
    tags: ["Frontier", "Reasoning"],
    notes: "Full reasoning model; 20% fewer major errors vs o1 on hard tasks",
  },
  {
    id: "o3-mini",
    name: "o3-mini",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2025-01-31",
    family: "o3",
    variantLabel: "mini",
    gpqa: 79.7,
    contextK: 128,
    costInput: 1.10,
    costOutput: 4.40,
    modalities: ["text", "code"],
    tags: ["Frontier", "Reasoning", "Cheapest"],
    notes: "Cost-efficient reasoning; strong on STEM and math",
  },
  {
    id: "o1",
    name: "o1",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2024-09-12",
    family: "o1",
    variantLabel: "o1",
    mmlu: 92.3,
    gpqa: 78.3,
    sweBench: 48.9,
    contextK: 128,
    costInput: 15,
    costOutput: 60,
    modalities: ["text", "code"],
    tags: ["Frontier", "Reasoning"],
    notes: "Introduced systematic chain-of-thought; breakthrough on PhD-level science tasks",
  },
  {
    id: "o1-mini",
    name: "o1-mini",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2024-09-12",
    family: "o1",
    variantLabel: "mini",
    contextK: 128,
    costInput: 3,
    costOutput: 12,
    modalities: ["text", "code"],
    tags: ["Frontier", "Reasoning", "Efficient"],
    notes: "80% cheaper than o1; strong coding and math performance",
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2024-05-13",
    family: "GPT-4o",
    variantLabel: "4o",
    mmlu: 88.7,
    sweBench: 30.8,
    contextK: 128,
    costInput: 2.5,
    costOutput: 10,
    modalities: ["text", "image", "audio", "code"],
    tags: ["Frontier", "Multimodal", "Agent-Ready"],
    notes: "First omnimodal model; real-time voice conversation capability",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2024-07-18",
    family: "GPT-4o",
    variantLabel: "mini",
    mmlu: 82.0,
    contextK: 128,
    costInput: 0.15,
    costOutput: 0.60,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Cheapest", "Fastest"],
    notes: "Replaced GPT-3.5 Turbo as the default cheap model",
  },
  {
    id: "gpt-4-turbo",
    name: "GPT-4 Turbo",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2023-11-06",
    family: "GPT-4",
    variantLabel: "Turbo",
    mmlu: 86.4,
    sweBench: 13.9,
    contextK: 128,
    costInput: 10,
    costOutput: 30,
    modalities: ["text", "image", "code"],
    tags: ["Frontier"],
    notes: "128K context; introduced vision, JSON mode, and improved function calling",
  },
  {
    id: "gpt-35-turbo",
    name: "ChatGPT (GPT-3.5)",
    provider: "OpenAI",
    providerColor: C.openai,
    type: "frontier",
    releaseDate: "2022-11-30",
    family: "GPT-3.5",
    variantLabel: "Turbo",
    mmlu: 70.0,
    gpqa: 28.0,
    contextK: 16,
    costInput: 0.50,
    costOutput: 1.50,
    modalities: ["text", "code"],
    tags: ["Frontier"],
    notes: "Sparked the public AI era; first widely-adopted conversational LLM",
  },

  // ── Google ─────────────────────────────────────────────────────────────────
  {
    id: "gemini-31-pro",
    name: "Gemini 3.1 Pro",
    provider: "Google",
    providerColor: C.google,
    type: "frontier",
    releaseDate: "2026-02-19",
    family: "Gemini 3.1",
    variantLabel: "Pro",
    mmlu: 90.5,
    gpqa: 94.3,
    contextK: 1000,
    costInput: 2,
    costOutput: 12,
    modalities: ["text", "image", "video", "audio", "code"],
    tags: ["Frontier", "Multimodal", "Largest Context"],
    notes: "ARC-AGI-2: 77.1%; ties GPT-5.4 Pro on Intelligence Index; leads 12/18 benchmarks",
  },
  {
    id: "gemini-31-flash-lite",
    name: "Gemini 3.1 Flash-Lite",
    provider: "Google",
    providerColor: C.google,
    type: "frontier",
    releaseDate: "2026-03-03",
    family: "Gemini 3.1",
    variantLabel: "Flash-Lite",
    contextK: 1000,
    costInput: 0.25,
    costOutput: 1.50,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Cheapest", "Fastest"],
    notes: "2.5× faster TTFT vs Gemini 2.5 Flash; matches 2.5 Flash quality at ⅛ the cost",
  },
  {
    id: "gemini-25-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    providerColor: C.google,
    type: "frontier",
    releaseDate: "2025-03-25",
    family: "Gemini 2.5",
    variantLabel: "Pro",
    contextK: 1000,
    costInput: 1.25,
    costOutput: 10,
    modalities: ["text", "image", "video", "audio", "code"],
    tags: ["Frontier", "Multimodal", "Reasoning"],
    notes: "Flagship of the 2.5 generation; strong at complex document and video understanding",
  },
  {
    id: "gemini-25-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    providerColor: C.google,
    type: "frontier",
    releaseDate: "2025-06-01",
    family: "Gemini 2.5",
    variantLabel: "Flash",
    contextK: 1000,
    costInput: 0.30,
    costOutput: 2.50,
    speedTPS: 300,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Fastest"],
    notes: "0.54s TTFT; joint 2nd on Chatbot Arena Leaderboard",
  },
  {
    id: "gemini-20-flash",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    providerColor: C.google,
    type: "frontier",
    releaseDate: "2025-02-05",
    family: "Gemini 2.0",
    variantLabel: "Flash",
    contextK: 1000,
    costInput: 0.10,
    costOutput: 0.40,
    speedTPS: 400,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Cheapest", "Fastest"],
    notes: "Ultra-fast multimodal; real-time streaming for live applications",
  },
  {
    id: "gemma-4-31b",
    name: "Gemma 4 31B",
    provider: "Google",
    providerColor: C.google,
    type: "open-source",
    releaseDate: "2026-04-02",
    family: "Gemma 4",
    variantLabel: "31B",
    contextK: 256,
    costInput: 0.20,
    costOutput: 0.20,
    modalities: ["text", "image", "code"],
    tags: ["Open Source", "Efficient"],
    notes: "Apache 2.0; built on Gemini 3 tech; Codeforces ELO jumped 110 → 2150 vs prior Gemma",
  },
  {
    id: "gemma-3-27b",
    name: "Gemma 3 27B",
    provider: "Google",
    providerColor: C.google,
    type: "open-source",
    releaseDate: "2025-03-12",
    family: "Gemma 3",
    variantLabel: "27B",
    mmlu: 78.9,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "image", "code"],
    tags: ["Open Source"],
    notes: "Multimodal open-weight model; best Gemma 3 variant at 27B scale",
  },
  {
    id: "gemini-15-pro",
    name: "Gemini 1.5 Pro",
    provider: "Google",
    providerColor: C.google,
    type: "frontier",
    releaseDate: "2024-05-14",
    family: "Gemini 1.5",
    variantLabel: "Pro",
    mmlu: 86.3,
    contextK: 1000,
    costInput: 1.25,
    costOutput: 5.0,
    modalities: ["text", "image", "video", "audio", "code"],
    tags: ["Frontier", "Multimodal", "Largest Context"],
    notes: "Pioneered 1M token context window in production",
  },
  {
    id: "gemini-15-flash",
    name: "Gemini 1.5 Flash",
    provider: "Google",
    providerColor: C.google,
    type: "frontier",
    releaseDate: "2024-05-14",
    family: "Gemini 1.5",
    variantLabel: "Flash",
    mmlu: 78.9,
    contextK: 1000,
    costInput: 0.075,
    costOutput: 0.30,
    speedTPS: 350,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Cheapest", "Fastest"],
    notes: "Optimised for speed at 1M token scale; very popular for production workloads",
  },

  // ── Meta ────────────────────────────────────────────────────────────────────
  {
    id: "llama4-maverick",
    name: "Llama 4 Maverick",
    provider: "Meta",
    providerColor: C.meta,
    type: "open-source",
    releaseDate: "2025-04-05",
    family: "Llama 4",
    variantLabel: "Maverick",
    mmlu: 85.5,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "image", "code"],
    tags: ["Open Source", "Multimodal"],
    notes: "MoE: 400B total / 17B active; multimodal; free to self-host",
  },
  {
    id: "llama4-scout",
    name: "Llama 4 Scout",
    provider: "Meta",
    providerColor: C.meta,
    type: "open-source",
    releaseDate: "2025-04-05",
    family: "Llama 4",
    variantLabel: "Scout",
    contextK: 10000,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Largest Context"],
    notes: "10M token context; MoE 109B total / 17B active",
  },
  {
    id: "llama33-70b",
    name: "Llama 3.3 70B",
    provider: "Meta",
    providerColor: C.meta,
    type: "open-source",
    releaseDate: "2024-12-06",
    family: "Llama 3.3",
    variantLabel: "70B",
    mmlu: 83.0,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Best for Coding"],
    notes: "Approaches Llama 3.1 405B on text tasks at a fraction of the size",
  },
  {
    id: "llama-32-vision",
    name: "Llama 3.2 11B Vision",
    provider: "Meta",
    providerColor: C.meta,
    type: "open-source",
    releaseDate: "2024-09-25",
    family: "Llama 3.2",
    variantLabel: "11B Vision",
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "image", "code"],
    tags: ["Open Source", "Multimodal"],
    notes: "First multimodal Llama; efficient vision + language model for edge deployment",
  },
  {
    id: "llama-31-405b",
    name: "Llama 3.1 405B",
    provider: "Meta",
    providerColor: C.meta,
    type: "open-source",
    releaseDate: "2024-07-23",
    family: "Llama 3.1",
    variantLabel: "405B",
    mmlu: 88.6,
    sweBench: 43.9,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Reasoning"],
    notes: "First open-source model to rival GPT-4o on many tasks; landmark for open AI",
  },
  {
    id: "llama-31-8b",
    name: "Llama 3.1 8B",
    provider: "Meta",
    providerColor: C.meta,
    type: "open-source",
    releaseDate: "2024-07-23",
    family: "Llama 3.1",
    variantLabel: "8B",
    mmlu: 73.0,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Fastest", "Efficient"],
    notes: "128K context at 8B scale; extremely popular for on-device deployment",
  },

  // ── xAI ─────────────────────────────────────────────────────────────────────
  {
    id: "grok-420",
    name: "Grok 4.20",
    provider: "xAI",
    providerColor: C.xai,
    type: "frontier",
    releaseDate: "2026-03-24",
    family: "Grok 4",
    variantLabel: "4.20",
    contextK: 2000,
    costInput: 20,
    costOutput: 60,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Reasoning", "Largest Context"],
    notes: "2M token context; 78% non-hallucination rate; IFBench instruction following #1",
  },
  {
    id: "grok-3",
    name: "Grok-3",
    provider: "xAI",
    providerColor: C.xai,
    type: "frontier",
    releaseDate: "2025-06-10",
    family: "Grok 3",
    variantLabel: "Grok-3",
    contextK: 1000,
    costInput: 3,
    costOutput: 15,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Multimodal"],
    notes: "Trained on Colossus with 10× compute vs Grok-2; joint 2nd on Arena Leaderboard",
  },
  {
    id: "grok-3-mini",
    name: "Grok-3 Mini",
    provider: "xAI",
    providerColor: C.xai,
    type: "frontier",
    releaseDate: "2025-04-09",
    family: "Grok 3",
    variantLabel: "Mini",
    gpqa: 79.0,
    contextK: 128,
    costInput: 0.30,
    costOutput: 0.50,
    modalities: ["text", "code"],
    tags: ["Frontier", "Reasoning", "Cheapest"],
    notes: "Efficient reasoning; strong STEM and math performance",
  },
  {
    id: "grok-2",
    name: "Grok-2",
    provider: "xAI",
    providerColor: C.xai,
    type: "frontier",
    releaseDate: "2024-08-13",
    family: "Grok 2",
    variantLabel: "Grok-2",
    mmlu: 87.5,
    gpqa: 56.0,
    contextK: 128,
    costInput: 2,
    costOutput: 10,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Multimodal"],
    notes: "Includes Aurora image generation; real-time X/Twitter data access",
  },

  // ── DeepSeek ────────────────────────────────────────────────────────────────
  {
    id: "deepseek-v4",
    name: "DeepSeek V4",
    provider: "DeepSeek",
    providerColor: C.deepseek,
    type: "open-source",
    releaseDate: "2026-03-09",
    family: "DeepSeek V4",
    variantLabel: "V4",
    sweBench: 81.0,
    contextK: 1000,
    costInput: 0.30,
    costOutput: 0.50,
    modalities: ["text", "image", "video", "code"],
    tags: ["Open Source", "Best for Coding", "Multimodal"],
    notes: "~1T param MoE, 37B active; 1M context; native multimodal; ~1/10th Claude Sonnet cost",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek-R1",
    provider: "DeepSeek",
    providerColor: C.deepseek,
    type: "open-source",
    releaseDate: "2025-01-20",
    family: "DeepSeek R1",
    variantLabel: "R1",
    gpqa: 71.5,
    sweBench: 49.2,
    contextK: 128,
    costInput: 0.55,
    costOutput: 2.19,
    modalities: ["text", "code"],
    tags: ["Open Source", "Reasoning", "Best for Coding"],
    notes: "Matched o1 on reasoning at a fraction of the cost; triggered global AI cost reset; MIT license",
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    providerColor: C.deepseek,
    type: "open-source",
    releaseDate: "2024-12-26",
    family: "DeepSeek V3",
    variantLabel: "V3",
    mmlu: 88.5,
    sweBench: 69.0,
    contextK: 128,
    costInput: 0.14,
    costOutput: 0.28,
    modalities: ["text", "code"],
    tags: ["Open Source", "Cheapest", "Best for Coding"],
    notes: "Shocked the industry with GPT-4-level quality at near-zero cost",
  },

  // ── Alibaba ─────────────────────────────────────────────────────────────────
  {
    id: "qwen36-plus",
    name: "Qwen 3.6 Plus",
    provider: "Alibaba",
    providerColor: C.alibaba,
    type: "frontier",
    releaseDate: "2026-03-31",
    family: "Qwen 3.6",
    variantLabel: "Plus",
    contextK: 1000,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Frontier", "Reasoning"],
    notes: "Free preview; always-on chain-of-thought; leads OmniDocBench v1.5 (91.2) and RealWorldQA",
  },
  {
    id: "qwen35-397b",
    name: "Qwen 3.5-397B",
    provider: "Alibaba",
    providerColor: C.alibaba,
    type: "frontier",
    releaseDate: "2026-02-01",
    family: "Qwen 3.5",
    variantLabel: "397B",
    contextK: 128,
    costInput: 0.11,
    costOutput: 0.44,
    modalities: ["text", "code"],
    tags: ["Frontier", "Cheapest"],
    notes: "MoE 397B / 17B active; LiveCodeBench v6: 83.6%; AIME26: 91.3%",
  },
  {
    id: "qwen25-coder",
    name: "Qwen 2.5 Coder 32B",
    provider: "Alibaba",
    providerColor: C.alibaba,
    type: "open-source",
    releaseDate: "2024-11-12",
    family: "Qwen 2.5",
    variantLabel: "Coder 32B",
    sweBench: 46.9,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Best for Coding"],
    notes: "Best open-source coding model on release; matched GPT-4o on HumanEval",
  },
  {
    id: "qwen25-72b",
    name: "Qwen 2.5 72B",
    provider: "Alibaba",
    providerColor: C.alibaba,
    type: "open-source",
    releaseDate: "2024-09-19",
    family: "Qwen 2.5",
    variantLabel: "72B",
    mmlu: 86.1,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source"],
    notes: "Top open-source general model of late 2024; strong multilingual performance",
  },

  // ── Mistral ─────────────────────────────────────────────────────────────────
  {
    id: "mistral-large-3",
    name: "Mistral Large 3",
    provider: "Mistral",
    providerColor: C.mistral,
    type: "open-source",
    releaseDate: "2025-12-02",
    family: "Mistral Large",
    variantLabel: "Large 3",
    mmlu: 84.0,
    contextK: 128,
    costInput: 3,
    costOutput: 9,
    modalities: ["text", "code"],
    tags: ["Open Source"],
    notes: "675B scale; open-weights with commercial use restrictions",
  },
  {
    id: "mistral-large-2",
    name: "Mistral Large 2",
    provider: "Mistral",
    providerColor: C.mistral,
    type: "frontier",
    releaseDate: "2024-07-24",
    family: "Mistral Large",
    variantLabel: "Large 2",
    mmlu: 84.0,
    contextK: 128,
    costInput: 3,
    costOutput: 9,
    modalities: ["text", "code"],
    tags: ["Frontier", "Best for Coding"],
    notes: "Strong multilingual; competitive with Claude 3.5 Sonnet on coding at launch",
  },
  {
    id: "codestral-22b",
    name: "Codestral 22B",
    provider: "Mistral",
    providerColor: C.mistral,
    type: "open-source",
    releaseDate: "2024-05-29",
    family: "Codestral",
    variantLabel: "22B",
    contextK: 32,
    costInput: 0.20,
    costOutput: 0.60,
    modalities: ["text", "code"],
    tags: ["Open Source", "Best for Coding"],
    notes: "Code specialist; fill-in-the-middle support; 80+ programming languages",
  },
  {
    id: "mixtral-8x22b",
    name: "Mixtral 8×22B",
    provider: "Mistral",
    providerColor: C.mistral,
    type: "open-source",
    releaseDate: "2024-04-10",
    family: "Mixtral",
    variantLabel: "8×22B",
    mmlu: 77.8,
    contextK: 64,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source"],
    notes: "MoE 141B total / 39B active; strong multilingual performance",
  },
  {
    id: "mixtral-8x7b",
    name: "Mixtral 8×7B",
    provider: "Mistral",
    providerColor: C.mistral,
    type: "open-source",
    releaseDate: "2023-12-11",
    family: "Mixtral",
    variantLabel: "8×7B",
    mmlu: 70.6,
    contextK: 32,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Efficient"],
    notes: "Pioneered sparse MoE at scale; matched GPT-3.5 quality at 13B active params",
  },
  {
    id: "mistral-7b",
    name: "Mistral 7B",
    provider: "Mistral",
    providerColor: C.mistral,
    type: "open-source",
    releaseDate: "2023-09-27",
    family: "Mistral 7B",
    variantLabel: "7B",
    contextK: 32,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Efficient", "Fastest"],
    notes: "Outperformed Llama 2 13B at smaller size; sparked the open-source efficiency race",
  },

  // ── NVIDIA ──────────────────────────────────────────────────────────────────
  {
    id: "nemotron-3-super",
    name: "NVIDIA Nemotron 3 Super",
    provider: "NVIDIA",
    providerColor: C.nvidia,
    type: "open-source",
    releaseDate: "2025-10-01",
    family: "Nemotron 3",
    variantLabel: "Super 49B",
    sweBench: 60.5,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Best for Coding"],
    notes: "49B params; highest open-weight SWE-Bench score for enterprise coding at launch",
  },
  {
    id: "nemotron-4-340b",
    name: "Nemotron-4 340B",
    provider: "NVIDIA",
    providerColor: C.nvidia,
    type: "open-source",
    releaseDate: "2024-06-14",
    family: "Nemotron 4",
    variantLabel: "340B",
    mmlu: 78.7,
    contextK: 4,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source"],
    notes: "Optimised for synthetic data generation; used to train other models",
  },

  // ── AWS ─────────────────────────────────────────────────────────────────────
  {
    id: "nova-premier",
    name: "Amazon Nova Premier",
    provider: "AWS",
    providerColor: C.aws,
    type: "frontier",
    releaseDate: "2025-04-30",
    family: "Nova",
    variantLabel: "Premier",
    contextK: 1000,
    costInput: 2.5,
    costOutput: 12.5,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Multimodal"],
    notes: "AWS Bedrock only; strong visual reasoning (MMMU); teacher model for distillation",
  },
  {
    id: "nova-pro",
    name: "Amazon Nova Pro",
    provider: "AWS",
    providerColor: C.aws,
    type: "frontier",
    releaseDate: "2024-11-20",
    family: "Nova",
    variantLabel: "Pro",
    contextK: 300,
    costInput: 0.80,
    costOutput: 3.20,
    modalities: ["text", "image", "video", "code"],
    tags: ["Frontier", "Multimodal"],
    notes: "Best price-accuracy in the Nova series; video understanding up to 30 min",
  },
  {
    id: "nova-lite",
    name: "Amazon Nova Lite",
    provider: "AWS",
    providerColor: C.aws,
    type: "frontier",
    releaseDate: "2024-11-20",
    family: "Nova",
    variantLabel: "Lite",
    contextK: 300,
    costInput: 0.06,
    costOutput: 0.24,
    modalities: ["text", "image", "video", "code"],
    tags: ["Frontier", "Cheapest"],
    notes: "Very low cost multimodal; ideal for high-volume document processing",
  },
  {
    id: "nova-micro",
    name: "Amazon Nova Micro",
    provider: "AWS",
    providerColor: C.aws,
    type: "frontier",
    releaseDate: "2024-11-20",
    family: "Nova",
    variantLabel: "Micro",
    contextK: 128,
    costInput: 0.035,
    costOutput: 0.14,
    modalities: ["text", "code"],
    tags: ["Frontier", "Cheapest", "Fastest"],
    notes: "Text-only; sub-millisecond latency; cheapest AWS-native option",
  },

  // ── Microsoft ────────────────────────────────────────────────────────────────
  {
    id: "phi-4",
    name: "Phi-4",
    provider: "Microsoft",
    providerColor: C.microsoft,
    type: "open-source",
    releaseDate: "2025-01-10",
    family: "Phi-4",
    variantLabel: "14B",
    contextK: 16,
    costInput: 0.06,
    costOutput: 0.14,
    speedTPS: 300,
    modalities: ["text", "code"],
    tags: ["Open Source", "Fastest", "Efficient"],
    notes: "14B params; strong MMLU-Pro and math relative to size",
  },
  {
    id: "phi-4-mini",
    name: "Phi-4 Mini",
    provider: "Microsoft",
    providerColor: C.microsoft,
    type: "open-source",
    releaseDate: "2025-02-05",
    family: "Phi-4",
    variantLabel: "Mini 3.8B",
    contextK: 16,
    costInput: 0.025,
    costOutput: 0.10,
    modalities: ["text", "code"],
    tags: ["Open Source", "Fastest", "Efficient"],
    notes: "3.8B params; on-device capable; strong reasoning per parameter",
  },
  {
    id: "phi-35-moe",
    name: "Phi-3.5 MoE",
    provider: "Microsoft",
    providerColor: C.microsoft,
    type: "open-source",
    releaseDate: "2024-08-20",
    family: "Phi-3.5",
    variantLabel: "MoE",
    mmlu: 78.9,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Efficient"],
    notes: "16 experts × 3.8B; 6.6B active params with performance of 65B+ dense models",
  },
];

// Last updated: April 2026
export const MODELS_LAST_UPDATED = "2026-04-07";
