export type ModelType = "frontier" | "open-source";
export type Modality = "text" | "image" | "video" | "audio" | "code";

export interface AIModel {
  id: string;
  name: string;
  provider: string;
  providerColor: string;
  type: ModelType;
  releaseDate: string; // ISO "YYYY-MM-DD"
  // Benchmarks — null = not publicly disclosed
  mmlu?: number;       // 0-100
  gpqa?: number;       // 0-100, graduate-level reasoning
  sweBench?: number;   // 0-100, software engineering tasks
  // Cost — 0 for self-hosted open-source
  costInput: number;   // $/1M tokens
  costOutput: number;  // $/1M tokens
  speedTPS?: number;   // approx tokens/sec or TTFT note
  contextK: number;    // context window in K tokens
  modalities: Modality[];
  tags: string[];
  notes?: string;
}

export const AI_MODELS: AIModel[] = [
  // ── Anthropic ──
  {
    id: "claude-opus-46",
    name: "Claude Opus 4.6",
    provider: "Anthropic",
    providerColor: "#f59e0b",
    type: "frontier",
    releaseDate: "2026-02-01",
    contextK: 1000,
    costInput: 5,
    costOutput: 25,
    modalities: ["text", "code"],
    tags: ["Frontier", "Reasoning", "Agent-Ready"],
    notes: "Leads Chatbot Arena Elo rankings (Feb 2026)",
  },
  {
    id: "claude-sonnet-46",
    name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    providerColor: "#f59e0b",
    type: "frontier",
    releaseDate: "2026-02-01",
    contextK: 200,
    costInput: 3,
    costOutput: 15,
    modalities: ["text", "code"],
    tags: ["Frontier", "Best for Coding", "Agent-Ready"],
    notes: "Preferred by 59% of developers over Opus 4.5; computer use capability",
  },
  {
    id: "claude-37-sonnet",
    name: "Claude 3.7 Sonnet",
    provider: "Anthropic",
    providerColor: "#f59e0b",
    type: "frontier",
    releaseDate: "2025-02-24",
    contextK: 200,
    costInput: 3,
    costOutput: 15,
    modalities: ["text", "code"],
    tags: ["Frontier", "Extended Thinking"],
    notes: "Extended thinking mode for complex reasoning chains",
  },
  // ── OpenAI ──
  {
    id: "gpt-54",
    name: "GPT-5.4",
    provider: "OpenAI",
    providerColor: "#10b981",
    type: "frontier",
    releaseDate: "2026-03-05",
    sweBench: 74.9,
    contextK: 1000,
    costInput: 2.5,
    costOutput: 10,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Multimodal"],
    notes: "33% fewer factual errors than GPT-5.2; Tool Search architecture",
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    providerColor: "#10b981",
    type: "frontier",
    releaseDate: "2024-05-13",
    mmlu: 88.7,
    sweBench: 30.8,
    contextK: 128,
    costInput: 2.5,
    costOutput: 10,
    modalities: ["text", "image", "audio", "code"],
    tags: ["Frontier", "Multimodal", "Agent-Ready"],
  },
  {
    id: "o3",
    name: "o3",
    provider: "OpenAI",
    providerColor: "#10b981",
    type: "frontier",
    releaseDate: "2025-04-16",
    sweBench: 69.1,
    contextK: 128,
    costInput: 10,
    costOutput: 40,
    modalities: ["text", "code"],
    tags: ["Frontier", "Reasoning"],
    notes: "20% fewer major errors than o1 on hard tasks; chain-of-thought reasoning",
  },
  // ── Google ──
  {
    id: "gemini-31-pro",
    name: "Gemini 3.1 Pro",
    provider: "Google",
    providerColor: "#3b82f6",
    type: "frontier",
    releaseDate: "2025-09-01",
    gpqa: 94.3,
    contextK: 1000,
    costInput: 2,
    costOutput: 12,
    modalities: ["text", "image", "video", "audio", "code"],
    tags: ["Frontier", "Multimodal", "Largest Context"],
    notes: "ARC-AGI-2: 77.1%; best price-to-performance among closed models",
  },
  {
    id: "gemini-25-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    providerColor: "#3b82f6",
    type: "frontier",
    releaseDate: "2025-03-25",
    contextK: 1000,
    costInput: 1.25,
    costOutput: 10,
    modalities: ["text", "image", "video", "audio", "code"],
    tags: ["Frontier", "Multimodal"],
  },
  {
    id: "gemini-25-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    providerColor: "#3b82f6",
    type: "frontier",
    releaseDate: "2025-06-01",
    contextK: 1000,
    costInput: 0.30,
    costOutput: 2.50,
    speedTPS: 300,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Fastest"],
    notes: "0.54s TTFT; joint 2nd on Arena Leaderboard",
  },
  {
    id: "gemini-20-flash",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    providerColor: "#3b82f6",
    type: "frontier",
    releaseDate: "2025-02-05",
    contextK: 1000,
    costInput: 0.10,
    costOutput: 0.40,
    speedTPS: 400,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Cheapest", "Fastest"],
  },
  // ── Meta ──
  {
    id: "llama4-maverick",
    name: "Llama 4 Maverick",
    provider: "Meta",
    providerColor: "#a855f7",
    type: "open-source",
    releaseDate: "2025-04-05",
    mmlu: 85.5,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "image", "code"],
    tags: ["Open Source", "Multimodal"],
    notes: "MoE: 400B total / 17B active; free to self-host",
  },
  {
    id: "llama4-scout",
    name: "Llama 4 Scout",
    provider: "Meta",
    providerColor: "#a855f7",
    type: "open-source",
    releaseDate: "2025-04-05",
    contextK: 10000,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Largest Context"],
    notes: "10M token context window; MoE 109B total / 17B active",
  },
  {
    id: "llama33-70b",
    name: "Llama 3.3 70B",
    provider: "Meta",
    providerColor: "#a855f7",
    type: "open-source",
    releaseDate: "2024-12-06",
    mmlu: 83.0,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Best for Coding"],
    notes: "Approaches Llama 3.1 405B performance on text tasks",
  },
  // ── DeepSeek ──
  {
    id: "deepseek-v4",
    name: "DeepSeek V4",
    provider: "DeepSeek",
    providerColor: "#60a5fa",
    type: "open-source",
    releaseDate: "2026-03-01",
    sweBench: 81.0,
    contextK: 128,
    costInput: 0.30,
    costOutput: 0.50,
    modalities: ["text", "code"],
    tags: ["Open Source", "Best for Coding"],
    notes: "Major leap from V3; strong agentic task execution",
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    providerColor: "#60a5fa",
    type: "open-source",
    releaseDate: "2024-12-26",
    mmlu: 88.5,
    sweBench: 69.0,
    contextK: 128,
    costInput: 0.14,
    costOutput: 0.28,
    modalities: ["text", "code"],
    tags: ["Open Source", "Cheapest", "Best for Coding"],
  },
  // ── xAI ──
  {
    id: "grok-3",
    name: "Grok-3",
    provider: "xAI",
    providerColor: "#ef4444",
    type: "frontier",
    releaseDate: "2025-06-10",
    contextK: 1000,
    costInput: 3,
    costOutput: 15,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Multimodal"],
    notes: "Trained on Colossus with 10× compute vs Grok-2; joint 2nd on Arena Leaderboard",
  },
  // ── Alibaba ──
  {
    id: "qwen35-397b",
    name: "Qwen 3.5-397B",
    provider: "Alibaba",
    providerColor: "#06b6d4",
    type: "frontier",
    releaseDate: "2026-02-01",
    contextK: 128,
    costInput: 0.11,
    costOutput: 0.44,
    modalities: ["text", "code"],
    tags: ["Frontier", "Cheapest"],
    notes: "MoE 397B / 17B active; LiveCodeBench v6: 83.6%; AIME26: 91.3%",
  },
  // ── Mistral ──
  {
    id: "mistral-large-3",
    name: "Mistral Large 3",
    provider: "Mistral",
    providerColor: "#f97316",
    type: "open-source",
    releaseDate: "2025-12-02",
    mmlu: 84.0,
    contextK: 128,
    costInput: 3,
    costOutput: 9,
    modalities: ["text", "code"],
    tags: ["Open Source"],
    notes: "675B scale; open-weights with restrictions",
  },
  // ── NVIDIA ──
  {
    id: "nemotron-3-super",
    name: "NVIDIA Nemotron 3 Super",
    provider: "NVIDIA",
    providerColor: "#76b900",
    type: "open-source",
    releaseDate: "2025-10-01",
    sweBench: 60.5,
    contextK: 128,
    costInput: 0,
    costOutput: 0,
    modalities: ["text", "code"],
    tags: ["Open Source", "Best for Coding"],
    notes: "49B params; highest open-weight SWE-Bench for enterprise coding",
  },
  // ── Amazon ──
  {
    id: "nova-premier",
    name: "Amazon Nova Premier",
    provider: "AWS",
    providerColor: "#f97316",
    type: "frontier",
    releaseDate: "2025-04-30",
    contextK: 1000,
    costInput: 2.5,
    costOutput: 12.5,
    modalities: ["text", "image", "code"],
    tags: ["Frontier", "Multimodal"],
    notes: "AWS Bedrock only; strong visual understanding (MMMU)",
  },
  // ── Microsoft ──
  {
    id: "phi-4",
    name: "Phi-4",
    provider: "Microsoft",
    providerColor: "#3b82f6",
    type: "open-source",
    releaseDate: "2025-01-10",
    contextK: 16,
    costInput: 0.06,
    costOutput: 0.14,
    speedTPS: 300,
    modalities: ["text", "code"],
    tags: ["Open Source", "Fastest", "Efficient"],
    notes: "14B params; strong MMLU-Pro and math for its size",
  },
];

// Last updated: March 2026
export const MODELS_LAST_UPDATED = "2026-03-29";
